Alterações concluídas!
fabricadesoftwareufs/AutomacaoSalasWeb pull request #179
Opened 2024-11-27 19:33 UTC by M4RCOSVS0

closed #177

2024-11-28 02:13 UTC, Vingreyck requested changes
Olhar revisão

2024-11-28 02:13 UTC, Vingreyck commented on Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Views/Usuario/Details.cshtml
> +                                    <p class="form-control">@Model.UsuarioModel.DataNascimento.ToString("dd/MM/yyyy")</p>
não precisa colocar na model o trecho da linha 22: "[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}"", uma vez que ja está especificada aqui

2024-11-28 02:30 UTC, M4RCOSVS0 commented on Codigo/ModuloDeSoftware/AutomacaoSalas/SalasWeb/Views/Usuario/Details.cshtml
> +                                    <p class="form-control">@Model.UsuarioModel.DataNascimento.ToString("dd/MM/yyyy")</p>
Precisa. Como estava a visualização da data estaca por exemplo 01-01-0001, eu apenas formatei a string para aparecer 01/01/0001

2024-11-28 02:37 UTC, Vingreyck approved these changes
ok

2024-11-29 11:49 UTC, Vingreyck approved these changes
Ficou ótimo os "*" escondendo o cpf!

2024-11-29 15:31 UTC, Miguelftt commented
Ok!

2024-11-29 17:23 UTC, merged